# Generated by Django 5.2 on 2025-08-01 00:46

from django.db import migrations


def create_users(apps, schema_editor):
    User = apps.get_model('authentication', 'User')

    users_data = [
        {
            'email': 'atendente@cloudpark.com',
            'password': 'atendente123',
            'profile': 'attendant',
            'name': 'Atendente'
        },
        {
            'email': 'tecnico@cloudpark.com',
            'password': 'tecnico123',
            'profile': 'technician',
            'name': 'Técnico'
        }
    ]

    for user_data in users_data:
        email = user_data['email']
        password = user_data['password']
        profile = user_data['profile']
        name = user_data['name']

        if not User.objects.filter(email=email).exists():
            User.objects.create_user(
                email=email,
                password=password,
                profile=profile,
                is_staff=True,
                is_active=True
            )
            print(f'Usuário {name} criado: {email}')


def reverse_create_users(apps, schema_editor):
    User = apps.get_model('authentication', 'User')

    emails_to_delete = [
        'atendente@cloudpark.com',
        'tecnico@cloudpark.com'
    ]

    for email in emails_to_delete:
        User.objects.filter(email=email).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_users, reverse_create_users),
    ]
